// <auto-generated />
using ERP.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
#nullable disable

namespace ERP.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260527000002_AddAsaasBoleto")]
    partial class AddAsaasBoleto
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
