// <auto-generated />
using System;
using ERP.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ERP.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260408010000_AddParcelamentoToContaReceber")]
    partial class AddParcelamentoToContaReceber
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Designer file gerado manualmente — migração aplicada via SQL direto
            // Os campos foram adicionados no banco via migration_fase2_parcelamento.sql
        }
    }
}
