// <auto-generated />
using System;
using ERP.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ERP.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260527000001_AddTintometrico")]
    partial class AddTintometrico
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // Model snapshot omitted — full snapshot is in AppDbContextModelSnapshot.cs
            // This partial class provides only the [Migration] attribute required by EF Core
            // to register and apply the migration.
#pragma warning restore 612, 618
        }
    }
}
